### ISSUE TITLE
不能进行多个人跟踪的吗？

### ISSUE THREAD

**Issue by Dreamskya** [wangshengyang1996/FaceTrackDemo#4]

**Comment by wangshengyang1996** [comment]
可以的，并没有做最大人脸限制，已有更好的实现。详见ArcFace2.0版本的android demo

**Comment by Dreamskya** [comment]
大神，你是指下载Arcface离线2.0的SDK，然后，里面那个demo吗？那个demo也可以用你现有的方法绑定ID值吗？


zhangtao@simtoo.com
 
发件人： wangshengyang
发送时间： 2018-11-30 15:58
收件人： wangshengyang1996/FaceTrackDemo
抄送： Dreamskya; Author
主题： Re: [wangshengyang1996/FaceTrackDemo] 不能进行多个人跟踪的吗？ (#4)
可以的，并没有做最大人脸限值，已有更好的实现。详见ArcFace2.0版本的android demo

**Comment by Dreamskya** [comment]
能不能在你的demo上，加上年龄，性别这些属性呢？我看lib的jar包，没有这两个接口。

**Comment by wangshengyang1996** [comment]
你要是想在这个上面加可以自己加下，但是不建议，没什么意义。我的这个demo有更详细的实现，就是ArcFace2.0的demo
