### ISSUE TITLE
出现报错

### ISSUE THREAD

**Issue by KenStive** [wangshengyang1996/FaceTrackDemo#5]
ftError = ftEngine.AFT_FSDK_InitialFaceEngine(Constant.APP_ID, Constant.FT_SDK_KEY, AFT_FSDKEngine.AFT_OPF_0_HIGHER_EXT, 16, 20);
maxFaceNum这个参数传20就报错了  官方文档最高能支持25
对应log  
![image](https://user-images.githubusercontent.com/5654545/51828424-8cd4da80-2326-11e9-9432-d53cc0dd1bf4.png)

**Comment by KenStive** [comment]
应该是ANR了

**Comment by wangshengyang1996** [comment]
这个也只是调用了虹软的sdk，如果有问题说明他们之前没判断。不过建议使用2.0版本，已经出了很久了

**Comment by KenStive** [comment]
如果在onPreviewFrame回掉里面添加性别识别和年龄识别，这个感觉是个耗时的操作。这种能放到子线程去做异步操作吗

**Comment by KenStive** [comment]
> 这个也只是调用了虹软的sdk，如果有问题说明他们之前没判断。不过建议使用2.0版本，已经出了很久了

如果在onPreviewFrame回掉里面添加性别识别和年龄识别，这个感觉是个耗时的操作。这种能放到子线程去做异步操作吗

**Comment by wangshengyang1996** [comment]
没问题的，sdk提供了接口，想怎么调用都是开发者的事情，但是要注意不要线程不安全地调用
